package OrderManagementApp;

/**
* OrderManagementApp/OrderServiceHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from OrderManagement.idl
*/

public final class OrderServiceHolder implements org.omg.CORBA.portable.Streamable
{
  public OrderManagementApp.OrderService value = null;

  public OrderServiceHolder ()
  {
  }

  public OrderServiceHolder (OrderManagementApp.OrderService initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = OrderManagementApp.OrderServiceHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    OrderManagementApp.OrderServiceHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return OrderManagementApp.OrderServiceHelper.type ();
  }

}
