package OrderManagementApp;


/**
* OrderManagementApp/OrderServiceHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from OrderManagement.idl
*/

abstract public class OrderServiceHelper
{
  private static String  _id = "IDL:OrderManagementApp/OrderService:1.0";

  public static void insert (org.omg.CORBA.Any a, OrderManagementApp.OrderService that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static OrderManagementApp.OrderService extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (OrderManagementApp.OrderServiceHelper.id (), "OrderService");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static OrderManagementApp.OrderService read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_OrderServiceStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, OrderManagementApp.OrderService value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static OrderManagementApp.OrderService narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof OrderManagementApp.OrderService)
      return (OrderManagementApp.OrderService)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      OrderManagementApp._OrderServiceStub stub = new OrderManagementApp._OrderServiceStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static OrderManagementApp.OrderService unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof OrderManagementApp.OrderService)
      return (OrderManagementApp.OrderService)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      OrderManagementApp._OrderServiceStub stub = new OrderManagementApp._OrderServiceStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
