package OrderManagementApp;


/**
* OrderManagementApp/OrderService.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from OrderManagement.idl
*/

public interface OrderService extends OrderServiceOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface OrderService
