package OrderManagementApp;


/**
* OrderManagementApp/Order.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from OrderManagement.idl
*/

public final class Order implements org.omg.CORBA.portable.IDLEntity
{
  public String username = null;
  public int chickenQuantity = (int)0;
  public int colaQuantity = (int)0;
  public double totalPrice = (double)0;

  public Order ()
  {
  } // ctor

  public Order (String _username, int _chickenQuantity, int _colaQuantity, double _totalPrice)
  {
    username = _username;
    chickenQuantity = _chickenQuantity;
    colaQuantity = _colaQuantity;
    totalPrice = _totalPrice;
  } // ctor

} // class Order
