package OrderManagementApp;

/**
* OrderManagementApp/OrderHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from OrderManagement.idl
*/

public final class OrderHolder implements org.omg.CORBA.portable.Streamable
{
  public OrderManagementApp.Order value = null;

  public OrderHolder ()
  {
  }

  public OrderHolder (OrderManagementApp.Order initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = OrderManagementApp.OrderHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    OrderManagementApp.OrderHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return OrderManagementApp.OrderHelper.type ();
  }

}
