package OrderManagementApp;


/**
* OrderManagementApp/OrderServiceOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from OrderManagement.idl
*/

public interface OrderServiceOperations 
{

  // For example: "Fried Chicken: $5, Cola: $1"
  String getMenu ();

  // Output: A confirmation message (e.g., "Order received: Total $X")
  String placeOrder (String username, int chickenQuantity, int colaQuantity);

  // Throws an error if no order exists for the username.
  String checkOrderStatus (String username);

  // For the manager role: returns all current orders as a formatted string.
  String viewCurrentOrders ();
  boolean managerLogin ();
  void managerDisconnect ();
} // interface OrderServiceOperations
